// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqdlvjwyrmamxqcqidwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxZGx2and5cm1hbXhxY3FpZHdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MDYxNzcsImV4cCI6MjA3MDQ4MjE3N30.22E9Onidd7OqK7geznLQjIzxfwIzNCIYPjGMUcLuwcI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});